# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-json
        exclude: "^tsconfig.json$"
      - id: detect-private-key
      - id: check-vcs-permalinks
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.1
    hooks:
      - id: remove-crlf
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.29.0
    hooks:
      - id: eslint
        args: ["--fix"]
        files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        additional_dependencies:
          - typescript
          - eslint
          - eslint-config-prettier
          - eslint-config-standard
          - eslint-plugin-import
          - eslint-plugin-node
          - eslint-plugin-prettier
          - eslint-plugin-promise
          - eslint-plugin-simple-import-sort
          - "@typescript-eslint/eslint-plugin"
          - "@typescript-eslint/parser"
