name: quality-check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NVMRC }}
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Show /dist tree
        run: tree -hC --dirsfirst dist/
      - name: Assert no test files in dist/
        run: "! find dist/ -iname '*.test.*' | grep '.'"
      - name: Run tests
        run: yarn test --coverage --coverageDirectory .coverage/
      - name: Upload coverage stats
        uses: codecov/codecov-action@v3
        with:
          directory: .coverage/
